APP_CONFIG_FILE_PATH = 'config/app_config.json'
LOG_CONFIG_FILE_PATH = 'config/log_config.json'
PATH_CONFIG = 'path_config'
ALGORITHM_CONFIG = 'algorithm_config'
IS_TEST_APP = 'IS_TEST_APP'
EXECUTE_TIMEOUT = 'execute_timeout'
ALGORITHMS_ENDPOINT = '/api/algorithms'
TIME_OVER_MSG = 'Время для выполнения алгоритма истекло'
